Form design
mohamadhase/Image-recognition-AML pull request #19
Opened 2023-03-15 04:06 UTC by Dana-Ismail

design for image form

2023-03-15 15:16 UTC, mohamadhase approved these changes

2023-03-15 15:16 UTC, mohamadhase requested changes
can you please write some comments about your code in the ts file ?

2023-03-15 15:45 UTC, Reema-Khaseeb approved these changes

2023-03-17 18:22 UTC, mohamadhase approved these changes

2023-03-17 18:22 UTC, merged